MODEL:
  DATA_DIM: 100
  SEQ_LEN: 100
  ENC_INPUT_DIM: 0
  IC_ENC_DIM: 100
  CI_ENC_DIM: 64
  CON_DIM: 64
  CO_DIM: 10
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 3
  DROPOUT_RATE: 0.05 # OVERWRITTEN
  CD_RATE: 0.0 # OVERWRITTEN
  CD_PASS_RATE: 0.0 # OVERWRITTEN
  SV_RATE: 0.0
  SV_SEED: 0
  CO_PRIOR_TAU: 10.0
  CO_PRIOR_NVAR: 0.1
  IC_PRIOR_VAR: 0.1
  IC_POST_VAR_MIN: 1.0e-4
  CELL_CLIP: 5.0
  CI_LAG: 1
TRAIN:
  DATA:
    DIR: /snel/home/brianna/projects/deep_learning_project/
    PREFIX: lfads
  PATIENCE: 5000 # Early stopping should be off
  BATCH_SIZE: 50
  MAX_EPOCHS: 10000
  MAX_GRAD_NORM: 200.0
  LOSS_SCALE: 10000.0
  ADAM_EPSILON: 1.0e-8
  LR: 
    INIT: 0.01 # OVERWRITTEN
    STOP: 1.0e-10
    DECAY: 1.0
    PATIENCE: 6
  ADAM_EPSILON: 1.0e-8
  L2:
    START_EPOCH: 0
    INCREASE_EPOCH: 50
    IC_ENC_SCALE: 0.0
    CI_ENC_SCALE: 0.0
    GEN_SCALE: 1.0e-4 # OVERWRITTEN
    CON_SCALE: 1.0e-4 # OVERWRITTEN
  KL:
    START_EPOCH: 0
    INCREASE_EPOCH: 50
    IC_WEIGHT: 1.0e-4 # OVERWRITTEN
    CO_WEIGHT:  1.0e-4 # OVERWRITTEN
  PBT_MODE: False
  TUNE_MODE: False
  LOG_HPS: True
  USE_TB: False
  MODEL_DIR: /snel/home/brianna/projects/deep_learning_project/210426_PBT/pbt_run_4/ # OVERWRITTEN
  OVERWRITE: True